//
// Created by a on 9/22/20.
//

#ifndef DNA_ANALYZER_PROJECT_MANGEMENT_ALL_ARGS_H
#define DNA_ANALYZER_PROJECT_MANGEMENT_ALL_ARGS_H

#include "save_args.h"



#endif //DNA_ANALYZER_PROJECT_MANGEMENT_ALL_ARGS_H
